steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Build Backend Image
    args: ['builds', 'submit', './backend',
           '--tag=$_REGION_ID-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPOSITORY/$_BACKEND_IMAGE_NAME:$COMMIT_SHA'
    ]
    waitFor: ['-']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Deploy Backend to Cloud Run
    args: ['run', 'deploy', '$_BACKEND_SERVICE_NAME',
           '--image=$_REGION_ID-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPOSITORY/$_BACKEND_IMAGE_NAME:$COMMIT_SHA',
           '--region=$_REGION_ID',
           '--platform=managed',
           '--allow-unauthenticated',
           '--port=8080',
           '--set-env-vars=PROJECT_ID=$PROJECT_ID,BQ_DATASET=$_BIGQUERY_DATASET,BQ_USER_ACTIONS_TABLE=$_USER_ACTIONS_TABLE'
    ]
    waitFor: ['Build Backend Image']

options:
  logging: STACKDRIVER_ONLY

substitutions:
  _REGION_ID: europe-west1
  _ARTIFACT_REGISTRY_REPOSITORY: cloudrisk-images
  _BACKEND_IMAGE_NAME: backend
  _BACKEND_SERVICE_NAME: backend
  _BIGQUERY_DATASET: cloudrisk
  _USER_ACTIONS_TABLE: user_actions
