#Creamos una imagen base, ambos scripts necesitan las mismas dependencias!!
FROM python:3.11-slim AS base  
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Creamos la imagen para el contenedor de la calidad del aire. Ejecuta el script de air_quality.py
FROM base AS air_quality
COPY air_quality.py .
CMD ["python", "-u", "air_quality.py"]

#Creamos la imagen para el contenedor del tiempo. Ejecuta el script de weather.py
FROM base AS weather
COPY weather.py .
CMD ["python", "-u", "weather.py"]